package io.github.lumpytales.poco.core.analysis.collector;

import io.github.lumpytales.poco.core.analysis.metadata.ClassMetaData;
import io.github.lumpytales.poco.core.analysis.metadata.FieldMetaData;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

/**
 * will just detect which collector classes should be created
 */
public class ClassCollectorDetector {

    /**
     * detect the which collector classes should be created
     *
     * @param classesOfInterest which should be generated by request
     * @param classMetaData complete meta data
     * @return collector classes which should be created
     */
    @SuppressWarnings("unchecked")
    public List<Class<?>> detect(
            final List<Class<?>> classesOfInterest, final ClassMetaData classMetaData) {
        if (classesOfInterest != null && !classesOfInterest.isEmpty()) {
            return Collections.unmodifiableList(classesOfInterest);
        }

        final var fieldMetaData = classMetaData.fieldMetaData();
        final List<? extends Class<?>> allClasses =
                fieldMetaData.stream()
                        .map(FieldMetaData::getField)
                        .filter(Objects::nonNull)
                        .toList();
        return (List<Class<?>>) allClasses;
    }
}
